# Generated by Django 5.0 on 2023-12-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionchain',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
